### ISSUE TITLE
Struggling with getting discourse-home-page to work with newest Discourse

### ISSUE THREAD

**Issue by madsl** [sylque/discourse-home-page#4]
Now since DiscPage works again https://github.com/sylque/discpage/issues/38, I now see that this plugin has also stopped working with the newest discourse. If I try to redirect to a DiscPage-enabled site (both logged in and not logged in), I always get the reply that the "site not existing or is private".

**Comment by sylque** [comment]
Thanks for reporting. Fixed in v1.0.5.

**Comment by madsl** [comment]
Thank you, works like a charm :)
